- hosts: 192.168.29.169
  vars_files:
  - vars1.yml

  tasks:
  - name: "Creating Directory for Mount"
    file:
              state: directory
              path: "{{ dvd_dir }}"

  - name: "Mount the dvd to the Directory"
    mount:
              src: "/dev/cdrom"
              path: "{{ dvd_dir }}"
              state: mounted
              fstype: "iso9660"

  - name: "Configuring Yum AppStream"
    yum_repository:
              baseurl: "{{ dvd_dir }}/AppStream"
              name: "dvd1"
              description: "dvd1 for AppStream packages"
              gpgcheck: no

  - name: "Configuing Yum BaseOS"
    yum_repository:
              baseurl: "{{ dvd_dir }}/BaseOS"
              name: "dvd2"
              description: "dvd2 for BaseOS packages"
              gpgcheck: no

  - name: "Installing HTTPD"
    package:
              name: "httpd"
              state: present
    register: x

  - name: "Creating WebServer Directory"
    file:
              state: directory
              path: "{{ doc_root }}"

  - name: "Copying Configuration File"
    template:
              dest: "/etc/httpd/conf.d/httpdi.conf"
              src: "httpdi.conf"
    when: x.rc == 0
    notify:
              - Restart service

  - name: "Copying WebPage"
    copy:
              dest: "{{ doc_root }}/index.html"
              content: "HTTPD is Ideompedent\n"
            
  - name: "start httpd service"
    service:
              name: "httpd"
              state: started

  - name: "Create firewall rule"
    firewalld:
              port: "{{ http_port }}/tcp"
              state: enabled
              permanent: yes
              immediate: yes

  handlers:
  - name: Restart service
    service:
              name: "httpd"
              state: restarted
